version: '3.1'

services:
  db:
    image: mysql
    container_name: accounts
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - accounts_data:/var/lib/mysql

volumes:
  accounts_data: